# Generated by Django 6.1.1 on 2026-10-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiclesevice_DB',
            fields=[
                ('vechicle_no', models.CharField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('register_address', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_name', models.CharField(max_length=10)),
            ],
        ),
    ]
